version: '3.7'

services:

  quasar:
    build:
      context: .
      target: build-stage

  nginx:
    build:
      context: .
      target: prod-stage
    restart: unless-stopped
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    depends_on:
    - quasar