import { ordersDto } from '@/modules/db/orders'

export function getColumns () {
  return [
    // {
    //   name: '_id',
    //   required: true,
    //   label: '_id',
    //   align: 'left',
    //   field: (row: orsersDto.IOrder) => row._id,
    //   format: (val: string) => `${val}`,
    //   sortable: false,
    // },
    {
      name: 'date',
      required: true,
      label: 'Date',
      align: 'left',
      field: (row: ordersDto.IOrder) => row.date,
      format: (val: string) => `${val}`,
      sortable: false,
    },
    {
      name: 'title',
      required: true,
      label: 'Title',
      align: 'left',
      field: (row: ordersDto.IOrder) => row.title,
      format: (val: string) => `${val}`,
      sortable: false,
    },
    {
      name: 'price',
      required: true,
      label: 'Price',
      align: 'left',
      field: (row: ordersDto.IOrder) => row.price,
      format: (val: string) => `${val}`,
      sortable: false,
    },
    {
      name: 'amount',
      required: true,
      label: 'Amount',
      align: 'left',
      field: (row: ordersDto.IOrder) => row.amount,
      format: (val: string) => `${val}`,
      sortable: false,
    },
    {
      name: 'vendor',
      required: true,
      label: 'Vendor',
      align: 'left',
      field: (row: ordersDto.IOrder) => row.vendor,
      format: (val: string) => `${val}`,
      sortable: false,
    },
    {
      name: 'seller',
      required: true,
      label: 'Seller',
      align: 'left',
      field: (row: ordersDto.IOrder) => row.seller,
      format: (val: string) => `${val}`,
      sortable: false,
    },
    {
      name: 'markers',
      required: true,
      label: 'Markers',
      align: 'left',
      field: (row: ordersDto.IOrder) => row.markers,
      format: (val: string[]) => `${val}`,
      sortable: false,
    },
    {
      name: 'link',
      required: true,
      label: 'Link',
      align: 'left',
      field: (row: ordersDto.IOrder) => row.link,
      format: (val: string) => `${val}`,
      sortable: false,
    },
    {
      name: 'actions',
      required: false,
      label: '',
      align: 'left',
      sortable: false,
    },
  ]
}
