import { accountsClasses } from '@/modules/db/subjects/accounts'

export function getColumns () {
  return [
    // {
    //   name: '_id',
    //   required: true,
    //   label: '_id',
    //   align: 'left',
    //   field: (row: accountsDto.IAccount) => row._id,
    //   format: (val: string) => `${val}`,
    //   sortable: false,
    // },
    {
      name: 'title',
      required: true,
      label: 'Title',
      align: 'left',
      field: (row: accountsClasses.IAccount) => row.dto.title,
      format: (val: string) => `${val}`,
      sortable: false,
    },
    {
      name: 'group',
      required: true,
      label: 'Group',
      align: 'left',
      field: (row: accountsClasses.IAccount) => row.dto.group,
      format: (val: string) => `${val}`,
      sortable: false,
    },
    {
      name: 'email',
      required: true,
      label: 'Email',
      align: 'left',
      field: (row: accountsClasses.IAccount) => row.dto.email,
      format: (val: string) => `${val}`,
      sortable: false,
    },
    {
      name: 'login',
      required: true,
      label: 'Login',
      align: 'left',
      field: (row: accountsClasses.IAccount) => row.dto.login,
      format: (val: string) => `${val}`,
      sortable: false,
    },
    {
      name: 'password',
      required: true,
      label: 'Password',
      align: 'left',
      field: (row: accountsClasses.IAccount) => row.dto.password,
      format: (val: string) => `${val}`,
      sortable: false,
    },
    // Text renders along as folding table element
    // {
    //   name: 'text',
    //   required: true,
    //   label: 'Text',
    //   align: 'left',
    //   field: (row: accountsClasses.IAccount) => row.dto.text,
    //   format: (val: string) => `${val}`,
    //   sortable: false,
    // },
    {
      name: 'link',
      required: true,
      label: 'Link',
      align: 'left',
      field: (row: accountsClasses.IAccount) => row.dto.link,
      format: (val: string) => `${val}`,
      sortable: false,
    },
    // {
    //   name: 'markers',
    //   required: true,
    //   label: 'Markers',
    //   align: 'left',
    //   field: (row: accountsClasses.IAccount) => row.dto.markers,
    //   format: (val: string) => `${val}`,
    //   sortable: false,
    // },
    {
      name: 'actions',
      required: false,
      label: '',
      align: 'left',
      sortable: false,
    },
  ]
}
