import { boot } from 'quasar/wrappers'
import VueMarkdownIt from 'vue3-markdown-it'
// import 'highlight.js/styles/monokai.css'
// import 'highlight.js/styles/a11y-dark.css'
// import 'highlight.js/styles/agate.css'
// import 'highlight.js/styles/an-old-hope.css'
// import 'highlight.js/styles/androidstudio.css'
// import 'highlight.js/styles/atelier-cave-dark.css'
// import 'highlight.js/styles/atelier-cave-light.css'
// import 'highlight.js/styles/atelier-dune-dark.css'
// import 'highlight.js/styles/atelier-dune-light.css'
// import 'highlight.js/styles/atelier-estuary-dark.css'
// import 'highlight.js/styles/atelier-estuary-light.css'
// import 'highlight.js/styles/atelier-forest-dark.css'
// import 'highlight.js/styles/atelier-forest-light.css'
// import 'highlight.js/styles/atelier-heath-dark.css'
// import 'highlight.js/styles/atelier-heath-light.css'
// import 'highlight.js/styles/atelier-lakeside-dark.css'
// import 'highlight.js/styles/atelier-lakeside-light.css'
// import 'highlight.js/styles/atelier-plateau-dark.css'
// import 'highlight.js/styles/atelier-plateau-light.css'
// import 'highlight.js/styles/atelier-savanna-dark.css'
// import 'highlight.js/styles/atelier-savanna-light.css'
// import 'highlight.js/styles/atelier-seaside-dark.css'
// import 'highlight.js/styles/atelier-seaside-light.css'
// import 'highlight.js/styles/atelier-sulphurpool-dark.css'
// import 'highlight.js/styles/atelier-sulphurpool-light.css'
// import 'highlight.js/styles/atom-one-dark-reasonable.css'
// import 'highlight.js/styles/atom-one-dark.css'
// import 'highlight.js/styles/atom-one-light.css'
// import 'highlight.js/styles/brown-paper.css'
// import 'highlight.js/styles/codepen-embed.css'
// import 'highlight.js/styles/color-brewer.css'
// import 'highlight.js/styles/dracula.css'
// import 'highlight.js/styles/dark.css'
// import 'highlight.js/styles/default.css'
// import 'highlight.js/styles/docco.css'
// import 'highlight.js/styles/vs.css'
import 'highlight.js/styles/vs2015.css'
// import 'highlight.js/styles/xcode.css'
// import 'highlight.js/styles/xt256.css'
// import 'highlight.js/styles/zenburn.css'

export default boot(({ app }) => {
  app.use(VueMarkdownIt)
})
